### ISSUE TITLE
Update `package.json` scripts for new monorepo structure

### ISSUE THREAD

**Issue by chrisfalaska** [AlaskaAirlines/auro-form#12]
# Script / Task Strategy

How will `auro-form` manage its `package.json` scripts?

```
npm run build:input

npm run build:radio

etc
```

## Potential solutions

- https://docs.npmjs.com/cli/v7/using-npm/workspaces
- https://turbo.build/repo/docs/crafting-your-repository/managing-dependencies
- https://lerna.js.org

## Dependencies

Possibly a dependency of: https://github.com/AlaskaAirlines/auro-form/issues/19

## Issues raised:

- [ ] [Update script set up to match what is the Generator](https://github.com/AlaskaAirlines/auro-form/pull/16#discussion_r1825972360)
- [ ] [Update script names](https://github.com/AlaskaAirlines/auro-form/pull/16#discussion_r1826029333)
- [ ] [Refactor the build script set up to what we use in the generator](https://github.com/AlaskaAirlines/auro-form/pull/16#discussion_r1825962671)
- [ ] [Handle all components](https://github.com/AlaskaAirlines/auro-form/pull/16#discussion_r1826024844)

**Comment by jason-capsule42** [comment]
This ticket is no longer needed and the work is tracked elsewhere.
