### ISSUE TITLE
Update `form` with new component registration logic & update input to latest version

### ISSUE THREAD

**Issue by chrisfalaska** [AlaskaAirlines/auro-form#21]
Update the `form` component to use the new component registration logic (example: https://github.com/AlaskaAirlines/auro-icon/issues/144)

- How will children components also take advantage of the custom registry (ie, `input`, `dropdown`, etc)?

## Issues raised

- [ ] [Update `form` with new registration logic](https://github.com/AlaskaAirlines/auro-form/pull/16#discussion_r1826012616)
- [x] #38 [Update `input/demo/api.html`](https://github.com/AlaskaAirlines/auro-form/pull/16#discussion_r1826014045)
- [x] #38 [Update `input/demo/index.html`](https://github.com/AlaskaAirlines/auro-form/pull/16#discussion_r1826014254)

**Comment by sun-mota** [comment]
There is a dup: #13

**Comment by sun-mota** [comment]
blocked by
#16 
https://github.com/AlaskaAirlines/auro-input/pull/356
https://github.com/AlaskaAirlines/auro-input/pull/357
