### ISSUE TITLE
Update build:docs with next stable version of auro-library

### ISSUE THREAD

**Issue by chrisfalaska** [AlaskaAirlines/auro-form#30]
FYI, `build:docs` does not do anything due to Auro-library's bug on `^2.9.0` and `2.8.0` has another bug to process `build:docs`. To fix this, we should wait for new stable version of auro-libarary. We can move on and address `build:docs` issue on a separate ticket.

_Originally posted by @sun-mota in https://github.com/AlaskaAirlines/auro-form/issues/16#issuecomment-2460144315_

**Comment by sun-mota** [comment]
auro-library@3.0.1 is now available but requires some changes on each components
