### ISSUE TITLE
auro-form: integrating components into Turbo monorepo

### ISSUE THREAD

**Issue by sun-mota** [AlaskaAirlines/auro-form#53]
### General Support Request

merge menu, combobox, select, datepicker, checkbox, radio, and latest input in `sunMota/componentIntegration`
into Turbo monorepo in `cfriedberg/19`

#### `sunMota/componentIntegration`
- [x] #28 
- [x] #26 
- [x] #43 
- [x] #27 
- [x] #41 
- [x] #38 
- [x] #39
 
####  `cfriedberg/19`
- [x] #48 
- [x] #51 
- [x] #50 

### Exit criteria

all components build, run, lint without errors in Turbo monorepo setup

**Comment by chrisfalaska** [comment]
Completed in https://github.com/AlaskaAirlines/auro-form/pull/84
