### ISSUE TITLE
Implement new mobile redesign

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-form#55]
### General Support Request

Implement full-screen mobile redesign

### Possible Solution

Design component from blueprint:
- https://www.figma.com/design/3TQhiKjQqQOKYqaqcO1zj2/Dropdown?node-id=3119-690&node-type=canvas&m=dev

### Exit criteria

Component styles match blueprint and get approval from design

**Comment by Patrick-Daly-AA** [comment]
Please see https://github.com/AlaskaAirlines/auro-dropdown/issues/263 for some use cases we want to ensure we cover.
